<a href="https://colab.research.google.com/github/Suraram-Spandana/MDS_LABORATORY/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1. Create Pandas Series and Data Frame from various inputs.
2. Import any CSV file to Pandas Data Frame and perform the following:
(a) Visualize the first and last 10 records.
(b) Get the shape, index and column details.
(c) Select/Delete the records (rows)/columns based on conditions.
(d) Perform ranking and sorting operations.
(e) Do required statistical operations on the given columns.
(f) Find the count and uniqueness of the given categorical values.
(g) Rename single/multiple columns.

In [ ]:
import pandas as pd
import numpy as np

# 1. Create a Pandas Series

# From a list
list_data = [1, 2, 3, 4, 5]
series_from_list = pd.Series(list_data)
print("Series from list:\n", series_from_list)

# From a NumPy array
array_data = np.array([6, 7, 8, 9, 10])
series_from_array = pd.Series(array_data)
print("\nSeries from NumPy array:\n", series_from_array)

# From a dictionary (keys become index)
dict_data = {'a': 10, 'b': 20, 'c': 30}
series_from_dict = pd.Series(dict_data)
print("\nSeries from dictionary:\n", series_from_dict)

# 2. Create a Pandas DataFrame

# From a dictionary of lists/arrays (common way)
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}
df_from_dict = pd.DataFrame(data_dict)
print("\nDataFrame from dictionary of lists:\n", df_from_dict)

# From a list of dictionaries
list_of_dicts = [
    {'Name': 'Eve', 'Age': 22, 'City': 'Rome'},
    {'Name': 'Frank', 'Age': 40, 'City': 'Berlin'},
    {'Name': 'Grace', 'Age': 32, 'City': 'Sydney'}
]
df_from_list_of_dicts = pd.DataFrame(list_of_dicts)
print("\nDataFrame from list of dictionaries:\n", df_from_list_of_dicts)

# From a NumPy 2D array
numpy_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_numpy = pd.DataFrame(numpy_2d_array, columns=['ColA', 'ColB', 'ColC'])
print("\nDataFrame from NumPy 2D array:\n", df_from_numpy)

In [ ]:
import pandas as pd

# Create a dummy employee.csv file for demonstration if it doesn't exist
# In a real scenario, you would have this file already.
csv_content = """
id,name,department,salary,start_date
1,John Doe,Sales,60000,2020-01-15
2,Jane Smith,Marketing,75000,2019-06-01
3,Peter Jones,Sales,62000,2021-03-10
4,Mary Brown,HR,55000,2018-11-20
5,David Lee,Engineering,90000,2022-02-28
6,Sarah Green,Marketing,70000,2020-09-15
7,Mike White,Sales,65000,2019-04-01
8,Laura Black,Engineering,95000,2021-07-01
9,Chris Blue,HR,58000,2018-03-01
10,Anna Red,Sales,68000,2022-01-01
11,Tom Grey,Marketing,72000,2020-05-01
12,Lisa King,Engineering,88000,2019-10-01
13,Paul Queen,HR,59000,2021-09-01
14,Nancy Jack,Sales,61000,2019-01-01
15,Kevin Prince,Marketing,78000,2022-03-01
"""

with open('employee.csv', 'w') as f:
    f.write(csv_content)

# Import the CSV file into a Pandas DataFrame
try:
    df_employee = pd.read_csv('employee.csv')
    print("Successfully imported 'employee.csv'\n")
except FileNotFoundError:
    print("Error: 'employee.csv' not found. Please make sure the file is in the correct directory.")
    df_employee = pd.DataFrame() # Create an empty DataFrame to avoid errors later

# (a) Visualize the first and last 10 records.
if not df_employee.empty:
    print("First 10 records:")
    display(df_employee.head(10))
    print("\nLast 10 records:")
    display(df_employee.tail(10))

    # (b) Get the shape, index and column details.
    print("\nDataFrame Shape:", df_employee.shape)
    print("\nDataFrame Index:", df_employee.index)
    print("\nDataFrame Columns:", df_employee.columns)
    print("\nDataFrame Info:")
    df_employee.info()

Successfully imported 'employee.csv'

First 10 records:

   id         name   department  salary  start_date
0   1     John Doe        Sales   60000  2020-01-15
1   2   Jane Smith    Marketing   75000  2019-06-01
2   3  Peter Jones        Sales   62000  2021-03-10
3   4   Mary Brown           HR   55000  2018-11-20
4   5    David Lee  Engineering   90000  2022-02-28
5   6  Sarah Green    Marketing   70000  2020-09-15
6   7   Mike White        Sales   65000  2019-04-01
7   8  Laura Black  Engineering   95000  2021-07-01
8   9   Chris Blue           HR   58000  2018-03-01
9  10     Anna Red        Sales   68000  2022-01-01

Last 10 records:

    id          name   department  salary  start_date
5    6   Sarah Green    Marketing   70000  2020-09-15
6    7    Mike White        Sales   65000  2019-04-01
7    8   Laura Black  Engineering   95000  2021-07-01
8    9    Chris Blue           HR   58000  2018-03-01
9   10      Anna Red        Sales   68000  2022-01-01
10  11      Tom Grey    Marketing   72000  2020-05-01
11  12     Lisa King  Engineering   88000  2019-10-01
12  13    Paul Queen           HR   59000  2021-09-01
13  14    Nancy Jack        Sales   61000  2019-01-01
14  15  Kevin Prince    Marketing   78000  2022-03-01

DataFrame Shape: (15, 5)

DataFrame Index: RangeIndex(start=0, stop=15, step=1)

DataFrame Columns: Index(['id', 'name', 'department', 'salary', 'start_date'], dtype='object')

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          15 non-null     int64
 1   name        15 non-null     object
 2   department  15 non-null     object
 3   salary      15 non-null     int64
 4   start_date  15 non-null     object
dtypes: int64(2), object(3)
memory usage: 732.0+ bytes

### (c) Select/Delete the records (rows)/columns based on conditions.

In [ ]:
# Select rows based on a condition (e.g., employees in 'Sales' department)
sales_employees = df_employee[df_employee['department'] == 'Sales']
print("\nEmployees in 'Sales' department:")
display(sales_employees)

# Select rows based on multiple conditions (e.g., salary > 70000 AND department is Marketing)
high_earning_marketing = df_employee[(df_employee['salary'] > 70000) & (df_employee['department'] == 'Marketing')]
print("\nHigh-earning employees in 'Marketing' department:")
display(high_earning_marketing)

# Select specific columns
name_salary_df = df_employee[['name', 'salary']]
print("\nDataFrame with only 'name' and 'salary' columns:")
display(name_salary_df)

# Delete a column (e.g., 'id' column) - creates a new DataFrame without the column
df_without_id = df_employee.drop(columns=['id'])
print("\nDataFrame after dropping 'id' column:")
display(df_without_id)

# Delete rows based on a condition (e.g., remove employees with salary less than 60000)
# Using .index to get the indices of rows to drop
rows_to_drop_idx = df_employee[df_employee['salary'] < 60000].index
df_filtered_salary = df_employee.drop(rows_to_drop_idx)
print("\nDataFrame after deleting rows with salary < 60000:")
display(df_filtered_salary)

In [ ]:
import pandas as pd

df = pd.read_csv("/Employee.csv")
print(df.head())

   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1

### (a) Visualize the first and last 10 records (from `df` loaded from `/Employee.csv`).

In [ ]:
if not df.empty:
    print("First 10 records of df (from /Employee.csv):")
    display(df.head(10))
    print("\nLast 10 records of df (from /Employee.csv):")
    display(df.tail(10))
else:
    print("The 'df' DataFrame is empty. Please ensure '/Employee.csv' was loaded correctly.")

First 10 records of df (from /Employee.csv):

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0
9,Masters,2017,New Delhi,2,37,Male,No,2,0

Last 10 records of df (from /Employee.csv):

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

### (b) Get the shape, index and column details.

In [ ]:
if not df.empty:
    print("\nDataFrame Shape:", df.shape)
    print("\nDataFrame Index:", df.index)
    print("\nDataFrame Columns:", df.columns)
    print("\nDataFrame Info:")
    df.info()
else:
    print("The 'df' DataFrame is empty. Cannot retrieve shape, index, or column details.")

DataFrame Shape: (4653, 9)

DataFrame Index: RangeIndex(start=0, stop=4653, step=1)

DataFrame Columns: Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

### (c) Select/Delete the records (rows)/columns based on conditions.

In [ ]:
# Select rows based on a condition (e.g., employees with 'Bachelors' education)
education_bachelors = df[df['Education'] == 'Bachelors']
print("\nEmployees with 'Bachelors' education:")
display(education_bachelors)

# Select rows based on multiple conditions (e.g., female employees in 'Pune' city)
female_in_pune = df[(df['Gender'] == 'Female') & (df['City'] == 'Pune')]
print("\nFemale employees in 'Pune' city:")
display(female_in_pune)

# Select specific columns (e.g., 'Education', 'Age', 'JoiningYear')
education_age_year = df[['Education', 'Age', 'JoiningYear']]
print("\nDataFrame with only 'Education', 'Age', and 'JoiningYear' columns:")
display(education_age_year)

# Delete a column (e.g., 'EverBenched' column) - creates a new DataFrame without the column
df_without_everbenched = df.drop(columns=['EverBenched'])
print("\nDataFrame after dropping 'EverBenched' column:")
display(df_without_everbenched)

# Delete rows based on a condition (e.g., remove employees who 'LeaveOrNot' is 1)
# Using .index to get the indices of rows to drop
rows_to_drop_idx = df[df['LeaveOrNot'] == 1].index
df_staying_employees = df.drop(rows_to_drop_idx)
print("\nDataFrame after deleting employees who left (LeaveOrNot == 1):")
display(df_staying_employees)

Employees with 'Bachelors' education:

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
...,...,...,...,...,...,...,...,...,...
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

Female employees in 'Pune' city:

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
1,Bachelors,2013,Pune,1,28,Female,No,3,1
18,Bachelors,2015,Pune,2,30,Female,No,0,1
28,Bachelors,2013,Pune,2,31,Female,No,2,1
34,Bachelors,2017,Pune,2,37,Female,No,0,1
38,Bachelors,2017,Pune,2,29,Female,No,2,1
...,...,...,...,...,...,...,...,...,...
4610,Bachelors,2015,Pune,3,24,Female,No,2,1
4620,Bachelors,2015,Pune,2,38,Female,No,4,1
4630,Bachelors,2012,Pune,3,25,Female,No,3,1
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0

DataFrame with only 'Education', 'Age', and 'JoiningYear' columns:

      Education  Age  JoiningYear
0     Bachelors   34         2017
1     Bachelors   28         2013
2     Bachelors   38         2014
3       Masters   27         2016
4       Masters   24         2017
...         ...  ...          ...
4648  Bachelors   26         2013
4649    Masters   37         2013
4650    Masters   27         2018
4651  Bachelors   30         2012
4652  Bachelors   33         2015

[4653 rows x 3 columns]

DataFrame after dropping 'EverBenched' column:

,Education,JoiningYear,City,PaymentTier,Age,Gender,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,0,0
1,Bachelors,2013,Pune,1,28,Female,3,1
2,Bachelors,2014,New Delhi,3,38,Female,2,0
3,Masters,2016,Bangalore,3,27,Male,5,1
4,Masters,2017,Pune,3,24,Male,2,1
...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,4,0
4649,Masters,2013,Pune,2,37,Male,2,1
4650,Masters,2018,New Delhi,3,27,Male,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,4,0

DataFrame after deleting employees who left (LeaveOrNot == 1):

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
8,Bachelors,2016,Pune,3,23,Male,No,1,0
...,...,...,...,...,...,...,...,...,...
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

### (d) Perform ranking and sorting operations.

In [ ]:
# Sort DataFrame by 'Age' in ascending order
df_sorted_age = df.sort_values(by='Age', ascending=True)
print("\nDataFrame sorted by 'Age' (ascending):")
display(df_sorted_age.head())

# Sort DataFrame by 'JoiningYear' in descending order
df_sorted_joining_year_desc = df.sort_values(by='JoiningYear', ascending=False)
print("\nDataFrame sorted by 'JoiningYear' (descending):")
display(df_sorted_joining_year_desc.head())

# Sort by multiple columns (e.g., 'City' then 'Age')
df_sorted_city_age = df.sort_values(by=['City', 'Age'], ascending=[True, False])
print("\nDataFrame sorted by 'City' (ascending) then 'Age' (descending):")
display(df_sorted_city_age.head())

# Add a rank to employees based on 'ExperienceInCurrentDomain'
# Using `method='dense'` to assign ranks without gaps
df['ExperienceRank'] = df['ExperienceInCurrentDomain'].rank(method='dense', ascending=False)
print("\nDataFrame with 'ExperienceRank' (ranked by ExperienceInCurrentDomain, highest experience first):")
display(df[['ExperienceInCurrentDomain', 'ExperienceRank']].sort_values(by='ExperienceRank').head(10))

# Rank within groups (e.g., rank employees by Age within each 'Education' group)
df['AgeRank_by_Education'] = df.groupby('Education')['Age'].rank(method='min')
print("\nDataFrame with 'AgeRank_by_Education' (ranked by Age within each Education group):")
display(df[['Education', 'Age', 'AgeRank_by_Education']].sort_values(by=['Education', 'Age']).head(10))

DataFrame sorted by 'Age' (ascending):

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4069,Masters,2013,New Delhi,2,22,Male,Yes,0,1
4539,Bachelors,2014,Bangalore,3,22,Female,No,0,0
4048,Bachelors,2014,Bangalore,3,22,Male,No,0,0
4070,Bachelors,2015,Pune,1,22,Female,No,0,1
4561,Bachelors,2013,Bangalore,3,22,Male,No,0,1

DataFrame sorted by 'JoiningYear' (descending):

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
1496,Bachelors,2018,Pune,3,27,Female,No,5,1
4596,Bachelors,2018,New Delhi,3,27,Female,No,5,1
4598,Bachelors,2018,Bangalore,3,31,Male,No,0,1
32,Bachelors,2018,Bangalore,3,26,Male,No,4,1
1546,Bachelors,2018,Pune,3,24,Male,Yes,2,1

DataFrame sorted by 'City' (ascending) then 'Age' (descending):

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
3004,Bachelors,2016,Bangalore,3,41,Male,No,0,0
3008,Masters,2017,Bangalore,3,41,Female,No,2,1
3017,Bachelors,2017,Bangalore,3,41,Male,Yes,3,0
3055,Bachelors,2012,Bangalore,3,41,Male,No,3,0
3114,Bachelors,2016,Bangalore,3,41,Male,No,1,0

DataFrame with 'ExperienceRank' (ranked by ExperienceInCurrentDomain, highest experience first):

      ExperienceInCurrentDomain  ExperienceRank
3985                          7             1.0
3960                          7             1.0
3962                          7             1.0
3971                          7             1.0
3989                          7             1.0
3982                          7             1.0
3978                          7             1.0
3975                          7             1.0
3988                          7             1.0
3964                          6             2.0

DataFrame with 'AgeRank_by_Education' (ranked by Age within each Education group):

      Education  Age  AgeRank_by_Education
5     Bachelors   22                   1.0
19    Bachelors   22                   1.0
25    Bachelors   22                   1.0
63    Bachelors   22                   1.0
91    Bachelors   22                   1.0
3991  Bachelors   22                   1.0
3993  Bachelors   22                   1.0
4021  Bachelors   22                   1.0
4024  Bachelors   22                   1.0
4025  Bachelors   22                   1.0

### (e) Do required statistical operations on the given columns.

In [ ]:
# Display basic descriptive statistics for numerical columns
print("\nDescriptive statistics for numerical columns:")
display(df.describe())

# Calculate the mean 'Age'
mean_age = df['Age'].mean()
print(f"\nMean Age: {mean_age:.2f}")

# Calculate the median 'JoiningYear'
median_joining_year = df['JoiningYear'].median()
print(f"Median Joining Year: {median_joining_year}")

# Calculate the mode of 'Education'
mode_education = df['Education'].mode()[0] # .mode() returns a Series, take the first if multiple modes
print(f"Mode Education: {mode_education}")

# Calculate the standard deviation of 'ExperienceInCurrentDomain'
std_experience = df['ExperienceInCurrentDomain'].std()
print(f"Standard Deviation of Experience In Current Domain: {std_experience:.2f}")

# Calculate the correlation matrix for numerical columns
print("\nCorrelation matrix for numerical columns:")
display(df.corr(numeric_only=True))

# Group by 'Education' and calculate the average 'Age' and 'ExperienceInCurrentDomain'
print("\nAverage Age and Experience by Education Level:")
display(df.groupby('Education')[['Age', 'ExperienceInCurrentDomain']].mean())

# Group by 'City' and find the maximum 'JoiningYear'
print("\nMaximum Joining Year by City:")
display(df.groupby('City')['JoiningYear'].max())

# Calculate value counts for a categorical column (e.g., 'Gender')
print("\nValue counts for 'Gender':")
display(df['Gender'].value_counts())

Descriptive statistics for numerical columns:

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot,ExperienceRank,AgeRank_by_Education
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864,5.094348,1356.042338
std,1.863377,0.561435,4.826087,1.558240,0.475047,1.558240,1108.884007
min,2012.000000,1.000000,22.000000,0.000000,0.000000,1.000000,1.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000,4.000000,371.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000,5.000000,1198.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000,6.000000,2339.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000,8.000000,3539.000000

Mean Age: 29.39
Median Joining Year: 2015.0
Mode Education: Bachelors
Standard Deviation of Experience In Current Domain: 1.56

Correlation matrix for numerical columns:

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot,ExperienceRank,AgeRank_by_Education
JoiningYear,1.000000,-0.096078,0.013165,-0.036525,0.181705,0.036525,-0.077991
PaymentTier,-0.096078,1.000000,0.007631,0.018314,-0.197638,-0.018314,0.084067
Age,0.013165,0.007631,1.000000,-0.134643,-0.051126,0.134643,0.772910
ExperienceInCurrentDomain,-0.036525,0.018314,-0.134643,1.000000,-0.030504,-1.000000,-0.131463
LeaveOrNot,0.181705,-0.197638,-0.051126,-0.030504,1.000000,0.030504,-0.079613
ExperienceRank,0.036525,-0.018314,0.134643,-1.000000,0.030504,1.000000,0.131463
AgeRank_by_Education,-0.077991,0.084067,0.772910,-0.131463,-0.079613,0.131463,1.000000

Average Age and Experience by Education Level:

                 Age  ExperienceInCurrentDomain
Education
Bachelors  29.422938                   2.910580
Masters    29.290951                   2.884307
PHD        29.296089                   2.910615

Maximum Joining Year by City:

City
Bangalore    2018
New Delhi    2018
Pune         2018
Name: JoiningYear, dtype: int64

Value counts for 'Gender':

Gender
Male      2778
Female    1875
Name: count, dtype: int64